# Aprendizaje Automático
#### Segundo cuatrimestre 2026

## Regresión Lineal

#### Bibliografía: 
* Pattern Recognition and Machine Learning, Christopher M. Bishop. Capítulo 3.
* The Elements of Statistical Learning, Trevor Hastie, Robert Tibshirani, Jerome Friedman. Capítulo 3.
* Para SVD, considerar este [link](https://www.youtube.com/watch?v=gXbThCXjZFM&list=PLMrJAkhIeNNSVjnsviglFoY2nXildDCcv&index=1). Con los primeros cuatro videos es suficiente para arrancar.
* Mathematics for Machine Learning, Marc Peter Deisenroth, A. Aldo Faisal, and Cheng Soon Ong. 

Papers:
* Ridge Regression: Biased Estimation for Nonorthogonal Problems, Arthur E. Hoerl and Robert W. Kennard, 1970.
* Regression Shrinkage and Selection via the Lasso, Robert Tibshirani, 1996.
* Regularization and variable selection via the elastic net, Hui Zou y Trevor Hastie, 2005.

### Repaso

La regresión lineal es un modelo que asume que la relación entre las variables de entrada $X^T = (X_1, X_2,..., X_p)$ y la variable de salida $Y$ es lineal. Entonces, toma la forma:

$$ f(X) = \beta_0 + \sum_{j=1}^{p} X_j \beta_j$$

En general, se suele escribir de la forma más compacta

$$ f(X) = X^T \beta$$

donde $X$ es un vector de tamaño $p+1$ que contiene un 1 en la primera posición y los valores de las variables de entrada en las siguientes posiciones. $\beta = (\beta_0, \beta_1, ..., \beta_p)$ es el vector de coeficientes a estimar.

### Repaso

El método más común para encontrar los coeficientes es el de **cuadrados mínimos**, que consiste en minimizar la suma de los residuos al cuadrado respecto de $\beta$. Utilizando notación matricial, esto se escribe como:

$$ RSS (\beta) = ||\textbf{y} - \textbf{X} \beta||^2 = (\textbf{y} - \textbf{X} \beta)^T (\textbf{y} - \textbf{X} \beta) $$

y la solución es:

$$ \hat{\beta} = (\textbf{X}^T \textbf{X})^{-1} \textbf{X}^T \textbf{y} $$

De esta forma, las predicciones $\hat{\textbf{y}}$ se obtienen como:

$$\hat{\textbf{y}} = \textbf{X} \hat{\beta} = \textbf{X} (\textbf{X}^T \textbf{X})^{-1} \textbf{X}^T \textbf{y}$$

Desde un punto de vista operativo, ya está. Obtuvimos un estimador de los coeficientes $\hat{\beta}$ que nos sirve para hacer predicciones. No hay, prácticamente, ninguna hipótesis sobre los datos, más allá de que $\textbf{X}$ tiene rango completo.

### Repaso

Si asumimos que $Var(\epsilon) = \sigma^2 I$, entonces:

$$Var(\hat{\beta}) = \sigma^2 (\textbf{X}^T \textbf{X})^{-1}$$

Podemos estimar $\sigma^2$ como 

$$\hat{\sigma}^2 = \frac{1}{N - p - 1} \sum_{i=1}^{N} (y_i - \hat{y}_i)^2 $$


### Máxima Verosimilitud



Otro método muy común es el de *máxima verosimilitud*. Dado el modelo $Y = f_\theta(X) + \epsilon$, el principio de máxima verosimilitud asume que los valores más *razonables* de $\theta$ son aquellos que maximizan la probabilidad de los datos observados. Para un conjunto de datos $(\textbf{X}, \textbf{y})$, la verosimilitud de los datos es la probabilidad conjunta de observar los datos dados los parámetros del modelo $\theta$:

$$ P(\textbf{y} | \textbf{X}, \theta) = P(y_1, y_2, ..., y_N | x_1, x_2, ..., x_N, \theta)$$

Si asumimos que los datos son independientes, la verosimilitud se puede escribir como el producto de las probabilidades individuales:

$$ \mathcal{L}(\theta) = P(\textbf{y} | \textbf{X}, \theta) = \prod_{i=1}^{N} P(y_i | x_i, \theta)$$

En general, es común trabajar con el logaritmo de la verosimilitud, que se puede escribir como:

$$ \log \mathcal{L}(\theta)  = \sum_{i=1}^{N} \log P(y_i | x_i, \theta)$$

**Notación:** cada $x_i$ es un vector de tamaño $p + 1$, e $y_i$ es un escalar.

### Máxima Verosimilitud

* Se suele asumir que los errores son independientes e idénticamente distribuidos (iid), bajo una distribución normal $\epsilon \sim \mathcal{N}(0, \sigma^2) $. Entonces, la probabilidad condicional de $y_i$ dado $x_i$ y $\theta$ se puede escribir como:

$$ P(y_i | x_i, \theta) = \mathcal{N}(f_\theta(x_i), \sigma^2) $$

$$ P(y_i | x_i, \theta) = \frac{1}{\sqrt{2 \pi \sigma^2}} e^{-\frac{(y_i - f_\theta(x_i))^2}{2 \sigma^2}}$$


Por lo que el logaritmo de la verosimilitud queda como:

$$ \log \mathcal{L}(\theta, \sigma^2) = -\frac{N}{2} \log(2 \pi ) - N \log \sigma - \frac{1}{2 \sigma^2} \sum_{i=1}^{N} (y_i - f_\theta(x_i))^2$$

* Entonces, para el modelo lineal $ Y = X^T \beta + \epsilon$, la verosimilitud se puede escribir como:

$$ \log \mathcal{L}(\beta, \sigma^2) = -\frac{N}{2} \log(2 \pi) - N \log \sigma - \frac{1}{2 \sigma^2} \sum_{i=1}^{N} (y_i - x_i^T \beta)^2$$

### Máxima Verosimilitud

#### Forma matricial

$$ \log \mathcal{L}(\beta, \sigma^2) = -\frac{N}{2} \log(2 \pi ) - N \log \sigma - \frac{1}{2 \sigma^2} (\textbf{y} - \textbf{X} \beta)^T (\textbf{y} - \textbf{X} \beta)$$

que, para maximizar respecto a $\beta$, solamente importa el término $-\frac{1}{2 \sigma^2} (\textbf{y} - \textbf{X} \beta)^T (\textbf{y} - \textbf{X} \beta)$, ya que el resto no depende de $\beta$. Entonces, la maximización de la verosimilitud es equivalente a minimizar la suma de los residuos al cuadrado, cuya solución es la que ya encontramos anteriormente.

Obtenido $\hat{\beta}$, podemos sustituirlo en la expresión de la verosimilitud y maximizar respecto a $\sigma^2$:

$$ \log \mathcal{L}(\hat{\beta}, \sigma^2) = -\frac{N}{2} \log(2 \pi) - N \log \sigma - \frac{1}{2 \sigma^2} (\textbf{y} - \textbf{X} \hat{\beta})^T (\textbf{y} - \textbf{X} \hat{\beta})$$

Lo que nos da la estimación de $\sigma^2$ como:

$$ \hat{\sigma}^2 = \frac{1}{N} (\textbf{y} - \textbf{X} \hat{\beta})^T (\textbf{y} - \textbf{X} \hat{\beta})$$

Como éste es un estimador sesgado, se suele utilizar:

$$ \hat{\sigma}^2 = \frac{1}{N - p - 1} (\textbf{y} - \textbf{X} \hat{\beta})^T (\textbf{y} - \textbf{X} \hat{\beta})$$

| Característica                      | Cuadrados Mínimos (general)                                                                 | Máxima Verosimilitud (general)                                                                   | Caso específico: Regresión Lineal Multivariada                                                                                                        |
|-------------------------------------|------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| Objetivo                            | Minimizar la suma de los residuos al cuadrado                                                                  | Maximizar la verosimilitud de los datos                                                             | Minimizar el error cuadrático entre predicciones lineales y observaciones                                                                                |
| Función objetivo                    | $\min_{\beta} \sum (y_i - f(\mathbf{x}_i, \beta))^2$                                             | $\max_{\beta} \prod p(y_i \mid \mathbf{x}_i, \beta)$                                                | $\min_{\beta} \sum (y_i - \mathbf{x}_i^T \beta)^2$                                                                                                       |
| Supuestos sobre errores             | Ninguno (aplicable a cualquier función de predicción)                                           | Distribución conocida del error (por ejemplo, normalidad)                                           | Normalidad, iid, media cero, varianza constante                                                                                                          |
| Resultado para la estimación de $\beta$ | Depende de la función $f(\mathbf{x}_i, \beta)$                                                   | Depende de la función de verosimilitud                                                             | $\hat{\beta} = (\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{y}$                                                                                 |
| Robustez                            | Depende de la elección de $f(\mathbf{x}_i, \beta)$                                               | Sensible a mal especificación del modelo                                                           | Sensible a outliers debido al error cuadrático                                                                                                           |
| Varianza de los errores             | No necesariamente explícita                                                                     | Incluida si se especifica la distribución                                                           | $\hat{\sigma}^2 = \frac{1}{N - p - 1} \sum (y_i - \mathbf{x}_i^T \hat{\beta})^2$                                                                              |
| Estimación de incertidumbre         | Depende de la función de predicción y supuestos adicionales                                       | Incluida en el modelo si se asume distribución                                                      | Utiliza la varianza estimada de los residuos                                                                                                             |
| Contexto típico                     | Modelos lineales o no lineales, regresión polinómica, redes neuronales, entre otros               | Modelos probabilísticos, GLM, modelos lineales generalizados                                        | Regresión lineal simple o múltiple                                                                                                                      |
| Extensión a modelos complejos       | Natural si se elige una función de predicción adecuada                                           | Natural para modelos probabilísticos                                                                | Se pueden incorporar regularizaciones (Ridge, Lasso)                                                                                                     |



**¿Qué pasa si $X$ no tiene rango completo?¿Qué pasa si hay predictores correlacionados o si hay multicolinealidad?**

### Singular Value Decomposition (SVD)

*"The SVD is like a mathematical Swiss Army knife"*

*'It has been referred to as the “fundamental theorem of linear algebra”'*


La descomposición en valores singulares (SVD) es una técnica que permite descomponer
**cualquier** matriz $X$ de tamaño $N \times p$ en tres matrices:

$$ X = U D V^T $$

Vamos a trabajar con la versión *thin* (o reducida), que asume $N \geq p$ —el caso
habitual: más observaciones que atributos—. En ella:

* $U$ es de tamaño $N \times p$ y tiene **columnas ortonormales**: $U^T U = I$.
* $D$ es una matriz diagonal de tamaño $p \times p$. Los valores en la diagonal cumplen
  que $d_1 \geq d_2 \geq \dots \geq d_p \geq 0$. Estos valores son los
  *valores singulares* de $X$.
* $V$ es una matriz **ortogonal** de tamaño $p \times p$: $V^T V = V V^T = I$.




El número de valores singulares **no nulos** es el rango $r$ de $X$. Entonces:

* Si algún $d_j = 0$, la matriz $X$ no tiene rango completo.
* Las primeras $r$ columnas de $U$ son una base ortonormal del **espacio columna** de $X$.
* Las primeras $r$ columnas de $V$ son una base ortonormal del **espacio fila** de $X$;
  las $p - r$ restantes son una base del **núcleo** de $X$ (las direcciones que $X$
  aplasta a cero).

**Nota:** se llama *ortogonal* a una matriz cuadrada $Q$ que cumple $Q^T Q = Q Q^T = I$.
Esto implica que $Q^{-1} = Q^T$ y que sus columnas son ortonormales (ortogonales entre sí
y de norma 1). Si la matriz no es cuadrada esto no puede pasar, y se habla de
*semi-ortogonalidad*: para $U$ de $N \times p$ con $N > p$ vale $U^T U = I_p$, pero
$U U^T \neq I_N$. Esa matriz $U U^T$ no es la identidad sino el **proyector ortogonal
sobre el espacio columna de $U$** (la vamos a reencontrar más adelante como la matriz
sombrero $\textbf{H}$).

### Singular Value Decomposition (SVD)

Algunas características:

* La formulación que acabamos de hacer de SVD no es única. En algunas formulaciones, las dimensiones de las matrices son un poco diferentes. En particular, la versión que les acabamos de contar se suele mencionar como SVD reducida o *thin*, que es la que se utiliza en la mayoría de los casos prácticos cuando $N \gt p$.

### Singular Value Decomposition (SVD)

<img src="Figuras/Reduced_Singular_Value_Decompositions.svg.png" alt="Figura 1" width="300" />

1. *Full SVD*
1. *Thin SVD*: eliminar columnas de $U$ no asociadas a filas de $V^T$.
1. *Compact SVD*: eliminar los valores singulares $d_j = 0$ y las columnas/filas correspondientes en $U$ y $V^T$.
1. *Truncated SVD*: quedarse con los $t$ mayores valores singulares y las columnas/filas correspondientes en $U$ y $V^T$.


### Singular Value Decomposition (SVD)

Algunas características:

* La formulación que acabamos de hacer de SVD no es única. En algunas formulaciones, las dimensiones de las matrices son un poco diferentes. En particular, la versión que les acabamos de contar se suele mencionar como SVD reducida o *thin*, que es la que se utiliza en la mayoría de los casos prácticos cuando $N \gt p$.
* Incluso dentro de una misma formulación, la descomposición no es única. 

Antes de pasar a su interpretación y cómo se calcula, veamos algunos ejemplos.


In [6]:
import numpy as np

X = np.array([[1, 1], [0, 1], [1, 2], [1, 3]])
# X = np.array([[1, 1], [1, 1], [1, 2], [1, 3]])
X = np.array([[1, 1, 1], [0, 1, 1], [1, 2, 2], [1,3, 3]])
X, np.linalg.matrix_rank(X)

(array([[1, 1, 1],
        [0, 1, 1],
        [1, 2, 2],
        [1, 3, 3]]),
 np.int64(2))

In [11]:
U, D, Vh = np.linalg.svd(X, full_matrices=False)
print(f'U: \n {U} \n')
print(f'D: \n {np.diag(D).round(3)} \n')
print(f'V^t: \n{Vh} \n')

U: 
 [[ 0.28718363  0.76432469  0.39451211]
 [ 0.23857053 -0.52575416  0.81604921]
 [ 0.52575416  0.23857053  0.02702499]
 [ 0.76432469 -0.28718363 -0.4215371 ]] 

D: 
 [[5.696 0.    0.   ]
 [0.    0.745 0.   ]
 [0.    0.    0.   ]] 

V^t: 
[[ 0.27690361  0.67945728  0.67945728]
 [ 0.9608977  -0.19580042 -0.19580042]
 [ 0.         -0.70710678  0.70710678]] 



In [9]:
print(f'U^t U: \n {U.T@U} \n')
# print(f'U U^t: \n {U@U.T} \n')

print(f'V^t V: \n{Vh@Vh.T} \n')

print(f'V V^t: \n{Vh.T@Vh} \n')
print(f'UDV^t: \n{ ((U @ np.diag(D)) @ Vh).round(2)} \n')

U^t U: 
 [[ 1.00000000e+00 -2.69568858e-16  3.53772024e-17]
 [-2.69568858e-16  1.00000000e+00 -1.79086648e-16]
 [ 3.53772024e-17 -1.79086648e-16  1.00000000e+00]] 

V^t V: 
[[ 1.00000000e+00  1.00003780e-16  1.46839452e-16]
 [ 1.00003780e-16  1.00000000e+00 -3.23293730e-17]
 [ 1.46839452e-16 -3.23293730e-17  1.00000000e+00]] 

V V^t: 
[[ 1.00000000e+00 -4.83349133e-18 -5.91879817e-18]
 [-4.83349133e-18  1.00000000e+00 -1.56386917e-16]
 [-5.91879817e-18 -1.56386917e-16  1.00000000e+00]] 

UDV^t: 
[[ 1.  1.  1.]
 [-0.  1.  1.]
 [ 1.  2.  2.]
 [ 1.  3.  3.]] 



### Singular Value Decomposition (SVD)

¿Qué son los *Valores Singulares*?

**Los valores singulares son la raíz cuadrada de los autovalores de la matriz $X^T X$**

Notar que estos autovalores son no negativos, ya que $X^T X$ es una matriz cuadrada semidefinida positiva.

In [14]:
print(f'X^T X: \n { X.T @ X} \n')
print((np.linalg.eigvals(X.T @ X)**(0.5)).round(3))
print(D.round(3))

X^T X: 
 [[ 3  6  6]
 [ 6 15 15]
 [ 6 15 15]] 

[5.696 0.745 0.   ]
[5.696 0.745 0.   ]


### Singular Value Decomposition (SVD)

**Interpretación geométrica**

1. $V^T$: rota (o cambia de base) en el espacio de entrada.  
2. $D$: escala cada dirección (dilatación o contracción).  
3. $U$: rota hacia el espacio de salida.  

Entonces, aplicar $X$ a un vector es como:

$$
\mathbf{x}
\xrightarrow{V^T}
\text{rotar}
\xrightarrow{D}
\text{escalar}
\xrightarrow{U}
\text{rotar}
$$


<img src="Figuras/Singular-Value-Decomposition.svg.png" alt="Figura 1" width="300" />


**Más general:**

La matriz $X$ de tamaño $N \times p$ se puede interpretar como una transformación lineal de $\mathbb{R}^p$ a $\mathbb{R}^N$. En la versión *full* de la descomposición, $U$ es $N \times N$ y $V$ es $p \times p$, ambas ortogonales: pueden pensarse como rotaciones (o reflexiones) de $\mathbb{R}^N$ y de $\mathbb{R}^p$, respectivamente. La matriz $D$, de tamaño $N \times p$, es la única que cambia la dimensión. Escala las primeras $\min(N, p)$ coordenadas por $d_1, \dots, d_{\min(N,p)}$ y luego:

* si $N > p$ (el caso habitual, más observaciones que atributos), completa el vector con $N - p$ ceros.
* si $N < p$, descarta las $p - N$ coordenadas sobrantes.

Es decir: $V^T$ y $U$ no modifican ni las longitudes ni las dimensiones; toda la deformación (el estiramiento a lo largo de cada dirección y el pasaje de $\mathbb{R}^p$ a $\mathbb{R}^N$) ocurre en $D$.


### Singular Value Decomposition (SVD)

¿Cómo se obtiene la descomposición?

* Existen métodos numéricos muy eficientes para calcular la SVD, disponibles en diversos lenguajes de programación y librerías.
* Esos métodos exceden los contenidos de la materia. Pero para tener una intuición,  veamos lo siguiente:

Si asumimos que existe $X = U D V^T$, usando la ortogonalidad de $U$ y $V$ se obtiene:

$$ X^T X = V D^T D\, V^T \qquad\qquad X X^T = U D D^T U^T $$

**En la versión *full*** ($U$ de $N \times N$, $V$ de $p \times p$, $D$ de $N \times p$),
las dos son descomposiciones en autovectores completas:

1. $X^T X = V \Lambda_p V^T$, con $\Lambda_p = D^T D$ diagonal de $p \times p$ y entradas
   $d_1^2, \dots, d_p^2$. Las columnas de $V$ son los autovectores de $X^T X$, y sus
   autovalores son los cuadrados de los valores singulares.
1. $X X^T = U \Lambda_N U^T$, con $\Lambda_N = D D^T$ diagonal de $N \times N$ y entradas
   $d_1^2, \dots, d_p^2$ seguidas de $N - p$ ceros. Las columnas de $U$ son los
   autovectores de $X X^T$. Los autovalores no nulos son los mismos que antes.

**En la versión *thin*** ($N \geq p$, con $U$ de $N \times p$ y $D$ de $p \times p$):

1. $X^T X = V D^2 V^T$ sigue siendo una descomposición completa, porque $V$ es cuadrada
   y ortogonal: no se perdió ningún autovector.
1. $X X^T = U D^2 U^T$ **no** lo es. Como $U$ es $N \times p$, aporta solamente $p$ de los
   $N$ autovectores de $X X^T$: los asociados a los autovalores $d_1^2, \dots, d_p^2$.
   Los $N - p$ autovalores restantes son cero, y sus autovectores son justamente las
   columnas que la versión *thin* descartó.

**¿Por qué no se calcula así?** Ésta es la parte que, numéricamente, puede "explotar".

* **Pensar el tamaño de las matrices:** $X^T X$ es $p \times p$, pero $X X^T$ es
  $N \times N$. Con muchas observaciones es inmanejable, tanto en memoria como en costo.
* Además, formar el producto $X^T X$ eleva al cuadrado el número de condición de $X$:
  se pierde precisión justo en los casos que nos interesan, los de multicolinealidad.
  Por eso los algoritmos reales calculan la SVD trabajando directamente sobre $X$, sin
  construir ninguno de los dos productos.


### Singular Value Decomposition (SVD)

#### Aplicaciones (en regresión lineal)

1. Regresión lineal con cuadrados mínimos:
    $$ \hat{\beta} = (\textbf{X}^T \textbf{X})^{-1} \textbf{X}^T \textbf{y}$$
    
    Se puede utilizar SVD para obtener una solución de mínimos cuadrados. Ésta toma la forma
    
    $$ \hat{\beta} = V D^{-1} U^T \textbf{y}$$

    donde $D^{-1}$ es la matriz diagonal que contiene los inversos de los valores singulares no nulos de $X$. Esto es particularmente útil si $X$ no tiene rango completo, ya que en este caso la matriz $\textbf{X}^T \textbf{X}$ no es invertible. ¿Por qué sucedería eso?

1. Dadas las predicciones $\hat{\textbf{y}} = \textbf{X} \hat{\beta} = \textbf{X} (\textbf{X}^T \textbf{X})^{-1} \textbf{X}^T \textbf{y}$
, a la matriz $ \textbf{H} = \textbf{X} (\textbf{X}^T \textbf{X})^{-1} \textbf{X}^T$ se la llama *matriz de proyección* o *sombrero* (*hat*) porque le pone un sombrero a los datos $\textbf{y}$ para proyectarlos en el espacio columna de $\textbf{X}$. Se puede ver con la descomposición SVD que la matriz de proyección es:

$$ \textbf{H} = \textbf{X} (\textbf{X}^T \textbf{X})^{-1} \textbf{X}^T = U D V^T (V D^2 V^T)^{-1} V D U^T = U D V^T (V D^{-2} V^T) V D U^T = U U^T$$

### Ejercicios

**Ejercicio:** Utilizando el dataset de *Prostate Cancer*:
1. Implementar un estimador de cuadrados mínimos con SVD.
1. Sumar a los predictores un predictor altamente correlacionado con uno de los existentes. También puede ser una combinación lineal de los otros atributos. ¿Qué ocurre con los coeficientes estimados?¿Qué ocurre con los valores singulares? 
1. En base a la descomposición SVD, ¿Cómo se puede hacer para que los coeficientes no se vean afectados por la multicolinealidad? Implementar. Investigar qué es la inversa de Moore-Penrose y cómo se relaciona con SVD.
1. Para el mismo grupo de atributos predictores, utilizar Scikit-learn para ajustar un modelo de regresión lineal. Comparar los coeficientes estimados por ustedes y los coeficientes estimados por Scikit-learn. ¿Son iguales? ¿Por qué?
